apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: production
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: ingress-resources
spec:
  ingressClassName: nginx
  rules:
    - host: fe.app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
