---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: production
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    .dockerconfigjson: AgCHD0yoePlZtccj0SUC6UuKcndSTfotNkr0+3I94r5lK9mM/lkMoGlMGZoPthdFthrJwy5FaWSvrskkJwaJnRCpHy91X7W48YJQipyoWbqbLBSZsz8t1OODEnKDIuvkhPZLG30NwSprsO6w+nRxODJclrYx8PVWM8D0qN1xANo0wIMTUr4Ju58oPf9x0PK8+AD5qsFxjR+qrDgv6Dld/HRbYP1apqk3wrWpCchWi10q+RNOMeo9R/qwodW4+XxvGTAXTDEC0qvKCPkSQ6/3nX6zS6Vygx6riVYi5VGRqPIpezeaJ2mb1I6xoGJmEl2abSRo4AoAmoIpJl9yl/VV7ftEbmi61gFUuvAdoJ23Y2IAXMMTyCFNBZkjFTXPCxDz9ZfTX2GwSVftyPHNOPaiudHtX0Ex1nCcet6Ul4NlzexDCNeO/kbOtMha3eWGZ9avO4PqAqPE2x7ekfNDIyEF2b0sBA/4YNf1htehZ7Nf3nmsEung8BekICla2DeNJpukVl7F5GAjLmoNovM+ctN09h/Ol3xCk1vuFsaL1/ZhFQiLvYdevdvnX0l6YGLqcxb8R5gI98vkU5B1/4MJOaj2uyp5vfEN0gJCoHTtmrLf+gmHVSmD2h42XHkMVk9fxfSkmwsYGlaGacXFufjpFHb4HMf0zYZGH3IP93+k9vVscCd4x693FuO2ji0rn5pV0+R6HPc8QNjdRhNY/sMi/DFFj7z5lwQTaNO7rbzrEe0Y6ikCnfa2W4FMa9cAvTdRotd97SuvFDvxpEgwQ7+h01FYVW6lu+kS7o6rzcNpXQnU0Yf6dBmeS1vtd7NEAIEpwQkvBLRx1W1NGggoC1Pblsjpi/VoMOaauZ7fphc69swreccP5iaMkXThvSMYfwRfQinEIhxwxPuTNV2JL0mdj7bM854EWCNtUrYfpRySus/W
  template:
    metadata:
      name: ghcr-secret
      namespace: production
    type: kubernetes.io/dockerconfigjson
