---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgA81ErGgD8Q7VJ+WPvQ+jzuZBtthFfa0LL0RIUuCUrnnoHNMX8ungG8ZF0SWa4/943d7wzaG0ratNXuy3QXoIUpZKjiS6yjvozbbQvpyyBzsUka1/968+P53FL81ExiLdDkUynEXmpGRp8xCrgGKgYEmyTSt3hdsSrDBxWDjrrlGqIeWX7lPByh+rvJE6zaO28IVa20iGtkH6qG862xownSgeOpzd/sSPaYy95iSZ9CJhXqT20JpUMXXRosNxDAf30PiW+1Qx+1IhLcFhRdPVxIcL6EGu1H+r9/tQfzhqLuFYtfpKwzGO7K7BYi2+iLmnsMvsftyCXGbXIvmnO7GorBjFwQXzhLiazFyHtjr36CBUITmauPKQw5D0Oztu0I6MJafizDKnwETKTQobp3hzXnsSHNOPfaPCpROfZok9WCViURGKYMrseDLFEeM1EVMas/0emafiO9+iFccIn9BIptxH6VWoJVXltlybEac7vxIbAzkR3g4KcG659sS3RwJELNVUhlICiSY9mlTg5Hux6ZdTU9TD6wmyYwl2hOSWgZuSFzQBnjNVLlr4ZMY1vHoF6KbC10sbocmNqZitzZ4c8GnzWtL5H1caRGIeFPgINprt3GZJUSoUFak1nCVYdNpfBoMgmvNj9TFDnA62AyK6Q8qVLjwan43F4QuH622NPb50P8KfCldZYgomtsdrjOimGRduomUJEN5wKeS9Pp6UCvW0+/00wq5x0CVR8pZG2AXxNikWPhH1pqWxjFimjBl2Jglnu/QcokEhYi3lefCtEhi1YozA8id/tsFaKJGKQj2oV12JNr/keOVL0UQYhWtU8egGtSVRhjscdxS3wVqtmhF9eUulQ7PkCkcrGqmttvocM2Yx0tdSnrcs+rist7UIk2s+C6xmBTaWdEzKphg9AtQCfjG5Y4OU9rxP9X
  template:
    metadata:
      name: ghcr-secret
      namespace: production
    type: kubernetes.io/dockerconfigjson
