---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opensearch-admin-secret
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: AgCVMdFmGZ269sg1i2zmvtXVXWrVV65NQm6tWrUtT/5dwiEiixrQSA/xO2S7HtCLJMZS2ajOh4qpSnodl/HUQ55k7cohKwYmARjyN1yA/xdbhy2dqfs2Gkw9ycBXsli3bXxl/Y5Np5Scv+DEkpZQyTwNevvusJLVKDLJGH+IcABlDuvUk7WolNQG4628TeUEV0Y2gbRqUlGFvxzKWUK8GxXm4SPkYM6/skIzfnlZwiOPkHK6x7xnrr7F+rAX/J4l56FJyXwFO95uUed9r7WilPIMEaRH7fVJLpfJfZMDuv6KSVKpLgg5xY0Qghi1kKAttpmJNyp1lVvcd9nfq6xkzKxGX+GkvjPT3VbVh9p8A/n1MEPSGCALtqY2vVO21VXsIpj0W/sBdP+a9diaO90DVF/O5P/cdbyVGTDY6FVA11RR0DBuPkxmWiadLHUgTSAEAasZGMvfmJKJaBc5aXtG5f94ZF4ojAGX3qNB38kU0IZB1Em2e/Y7yaPjPG2dzqG/ovtaaLyMKICm1KWlcp9KQ/RHX8dhBisXszziy7CT47RKPQenyw2DxaVyImj2XOc8doh2oWKgyZAUpxtI1uT5hx5BOI6WLURhspbdMPh+a73NDdoLYjOTzFCRABmhgKeFyzIupvvBhPtd5wNOnTwJFAD5Xna7eH4fMsbAbRWTJhYck1bh3/BoWg5QVjPt0SSyKI2l9oOOqmlA+Q2lu0pk
  template:
    metadata:
      name: opensearch-admin-secret
      namespace: monitoring
    type: Opaque
