namespace: production

replicaCount: 1

image:
  repository: ghcr.io/uit-devops-project/frontend-app
  tag: v2.0.6

imagePullSecret: ghcr-secret

nodeSelector: app-nodes

service:
  port: 80

ingress:
  host: fe.app.local
  
env:
  API_BASE_URL: /api
