namespace: production

replicaCount: 3

image:
  repository: ghcr.io/uit-devops-project/backend-app
  tag: latest

imagePullSecret: ghcr-secret

nodeSelector: app-nodes

command: "/app/node_modules/.bin/prisma migrate deploy && node src/server.js"

service:
  port: 3000

ingress:
  host: fe.app.local

database:
  secretName: postgres-secret