---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgCYHCkZOlp7iM32A5PYezjQ2bFxVTyngkjN37GzuwEWt3PnVhzs1Vz6KgT0MINQ3D2ayOILThLmYqc+X0p2+zxAv9oiGbA27VJfMKDuNQaliENGYWeYGAZ2C2RCn3Aam64T8OLguxv/Ql9OWt83sExmz5QJqvWHfOoZlncvPxXJ5my9JTBvc1MIUZCmr3BqzHkIauhC5T7OY52d8E1dix+SNh3G6bpKH4JfMHkvQMqngBm8Dg2TC9CG/YTKUN+vFBeRJZguvzOUXBRiJn20oYBR374sAdTOMAn5fPMEgU0agkVzWe2xRiw+1trvrtet6EPtts7F0jyNTm7lzaV59mBKYX/7b2trxFraVadcL1ZvIdBXlZlgXr7Q9DnFkCJPfxxNkqAxn7JLkCArDsZamecjlIOVkaPZjSucp/CDOpdLctFzGti8k8XEl/dZIw+6GV6VySJa9R8NTlhd2ErhMesPIhUd/QaNZWuwrD5359rcI+6oWAiY6mR5yZ7b4XhH8tYBxpuV1mWLG0qMV72Eye0VplwdHAf6XBI58tcRwNXLfhF0yCpIHMV8D2PAkYFic78W1LH2vdejd3ID/A30N+QQOf+fn+piLT9mkPoyuJBAhJJuLbiIvf9Ckx9zRl8kDUJDGlT2reIPX6syKxtPXaQrDVt/l018xBgDsfn0/xtFEwAM4QCLd3UDSWcKPK6Nye1HG5TE3J0CJncN2qF30AjB+yTQjunMWUJwcdZm7oMa857dLmbzbz6TVyB+DHmuLZF/opkPFwkPXzfW3Bgmd7X1+XzfJFlwFG+dV1qnpdZoScl0hjlwOActfztZLvlB9Owuacf7COhgk1gzcWsvXUNw/dgCcCztwCyQcyLQlnqsiGqa2yCmPH7bh0MHfblmk2beKfNhNm8zTnNMFHzJsuA1m6n231JgOiyTrDSf
  template:
    metadata:
      name: ghcr-secret
      namespace: staging
    type: kubernetes.io/dockerconfigjson
