---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: staging
spec:
  encryptedData:
    DATABASE_URL: AgA1zmoFi1yg0o4CDiyvumxn5TN5wQgPYW314elbxVeuzfps1iZ/pBwuEBj3kNFWk4qrbdmnVg8MKmywCiPEzSqqY3ZQfUCNrqXx4Mo2ZDE/uzYY3TuF/iU6fIpyWzXSZC12c99UKSmDFLcV0KZpNLkoz+jFztPrbo01FzzjuIAsPh2z5Y4QcGEaE/1lzljhDJdyiK9zjRxHsE/Y2kSao9PrkbqwPo7s8arpBBaK4XqYnvm3WDcoOQZqxNUt4AxRLdR/IsKkuuzAvoXl0nMVdEVW1TsmBgJ46IgH+5asIORXb57USGb5IMO0kpv7uuZRAyuKKEl59IHL8rj9AqVsZ80OJIc2wRBvsoI0B4riBaEyKDBvgvT0ek4hQMrhdU0EAtUwHnfirf+fNZfA9nW3PvgdxJ4VNwNafC+fBwmyyDYAPYfEywp7K951SloPXfHbaYK/du5wWKPEbKLsm43pEbNkRUK2FCNAxDXV6iSKIvukb1eI7t4m5FAssydienlyCevHv2OAxhYyUlhVTAEOcff4qP56FnKFZMMa34Kqs9uAaUhtsXV1PZjsYDgbTynKhOJrB1gHgtdgbjCPKim1oyAllI6SIqfQS6PAqywcKgyWTwUsxTxJnts0PLqHAi3qGKhPxb4R7SecK65V9Cv6WPGwaSOojucKutRTL1ZNzricPGabj+K4fjCMlI0N8T5FH4KkXgOShE5slNQXGDBtH5LYbrG+kpyCjS4XLflIBABCSJKoED/lpSc8Ng6lR0uUXskLaJxOrAw3JoULrvAdpuyaz01+dqzfq+BP38kmZM3xPQMCADW9QejHhOp7XZAi9z8iXmasJCX37R0HEhqKbKJJZY68HxYxIz8lTGmgu6b/qJEyhcY=
  template:
    metadata:
      name: postgres-secret
      namespace: staging
