---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgA4Aam+FmGWf2ZolRLqsBKFK6/FWXAbJLMD52BGDQYSN8F6fGAFy2LtB3O02pQrG/Je7Zg8zXM5pryVlyaCt2P0aiAR8UtmMpKCGKfq0mNmvvP7HAy/6u+4bxCnR6qkp4gQOGtIJld80ODuCTWWqzLqNPGr5JMMpt40f3THBfEZPsq1Zfl5HFIlkdxckTH1Cab1FLiKCql7msJS/Gh/Y5o/o50SfqRhzJmkzVOSmoKymuuTMCh4eI+/RkJQjVBTfympW7WDfHXrsHrOvX6j9g0K0mRbm5NDLs155SxVGHKviC4DCMSjRz+dcjAScP1qTt0CYIEpCU25QSzRmcv1FVzu3qBXoo61tkCgd2WTuw5cbcuF0/mCVrCBK3telWNd34OzmujZnUPPcav+8jff/yKo9rp4+deW5tb6NtybxzlUn1Lcwqty16oewMap3beLlmoyS6ci20A0xBYsgSlS+DPxB6ARV0ctsn13yJzhsKWpbOjvoqxGhupbnMfNVcNsYn7C5+9Gf3X+li8Ciq8KYDkzyqByqBZcURfo+YGdgvjVmAbUxft1Tok7fowpiqbvVeFEUOgVkjRZnh8k8ocfGizjR1+xtfVqMh3ZN1C/3u6T/yTIXDqABSOw9z+gq9z5Nk9GYa7sOyuEv49+xA7KEGdBF2m9GsxMTC/yoGToUNr92onT2u3mmHOmVbiLIIWlMcaxOdFvRinRiNVX7WYHR0qsx1uJzUg8QXrPZcP8X4Nd8Wv6gV4cYmbN69bBmynmKMkIo4Poj8++ye3MAaAlooprnzpJ2SEuTBnSd0CLdpoZ8AnIIhNEQHp2WQtxhN9W4Y/3/iSw8pQom3efqvDqlrz4Vmz8s2NUE4136dyXLaxslIoCPuotdUVdgtC67oTo3WsUAGICKgR+bq566t/S2YGjToZYVlUnFsWEExFP
  template:
    metadata:
      name: ghcr-secret
      namespace: production
    type: kubernetes.io/dockerconfigjson
