---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: production
spec:
  encryptedData:
    DATABASE_URL: AgCuYfl1FK4TjPLhY1Nn6s6jNytJq6mOglCPtDMj7/f0a1w1GROTlaCkNrrtNwBi0CmbK+FrgegeHWPOefQINOdj+cjVwWvzT7tcu9PU+dZYcerG5TWXPzstMkWViXKMc0J6v+H8agv5cQ4Of7tfX3vxcfzBmdXwYrOMUjPznISMXQNSK6hQtZoWmIkOW6mjuxyNEojKvBBwSQDo2iLvduKZ+gzy9p75LKUntaJPvfNICjDTFjLPrBXq068ziWlu+5wT927SNqudoPszWKvaFZf2xwR0+13DRUSt/m7sjpjOT/cqIBChNbo7q5/2nOUnLOqq5xdDUlPOcdpFKhA/uWjFGf4WfxDOrh9Do0phP9jJuM2zidkC5QJXMyccpRBeCriF3XiT8aae6x4+txV5Kb8Vpgo0U0VAm1QnD7DSW+k7+L2dzpIyf5zzYkrHPWO7pedbvnop8Td0fI6ZMpFKU95GZjBMewY/hy37zzOrWafz8yVuXzf7Ku4vXoc7Up4Er0UsrcJgMpx0Ji0VHvPJX0RTP99CW10xwDHxjdh+RZbESBWEgkM0oDLWl2MswcJ3YnKsOJ3xMBEqoKXH/k0Tgk/dsFRcatqGlxlaWe+3gIGRtYJSeBsyX54iCPACg1hV8NbTaN6JqQClY7WFSex3iHYCWcFrWTxVY7pJCrka+VohWxeIUzVJyawdCsblNY1kJKG1YSl/aRxBc6R/EJUy4h/JeyKVfOnHdcCe8CetrpcizSVggchRdjpM7pBUo4WYHleFWQ4GWdHhwBIXflJzNEiwNEFyFhx2MapBF7NQSQjDW5Mccugh0KnWI/qwTYkd4HlvvtbVFz958NPmCWJGhe79LHPnh0uIR4mfl5cB54YjXrjOIpZPJNs=
  template:
    metadata:
      name: postgres-secret
      namespace: production
