---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgBZC7Loz6mSq2Tj8lKTOW7agG9MbXcTcKUzV5GSfJY3N0UFLQf9OXAG0/fERGRH2T9DhJh3+ps8uCa+GvJeJpp4vhCwSo3oFcQUrRsq+NCfvjH1Bs3R5Owu1yLdpCI05eN2XcxAdthH2wvQHmJRylXrUPVEt+aeVZAWLYK72jqDpt7A/+TSnZY6b77t3p1WrI76gSG58DFQa2y2rMsR0c2Tv22L5nGnUQx0ucrrr8iwsDHYBZU1ijbUf/qJOut0VReg31eDVwskWXZ499pypaeGDJQ7bCPkZJhCnfDMnWs4Xne55vFax+pcV2JtZlVDXT8M/iDUxBq4jVV8J3TjZeQoiJGwdrIWQkMV5mU3P/IXvDRy9DvbbfjfcHsNUm41CZh/yYvv3e0ioUnTIxh+enI2udWIFfvQJX+8dfAxmeuyF0BmjIkV6GO3N79SYs1enkMlqKYQZ6TYZiiDnaGgdXkw40Q5Np/tj+QiJBIBS8z9Fz6YlyglUWuK3oHYf0TQP+e0Atp7qSijADvOh36dUl1at/x/h+mgThxoplqQvKxX8AqLu8dArQRhGRTm/Rw1koWV40n01coWrGI/K0XkvV45RV/U+bIrIO29olx2T2Uj/ImPDLOWXF65BIqlrwUwWSX8z8uYq/kaQgRIqtNz1Xoum/F3cnQHAkdirISMWR4bCddW/XlUyrJuvhN+0e9IAPtl1quSGpa+yrtG6rW2xDG8i7XUjLy4rlvZZWo968CZ3Z48Q+lBdqn6SzbSjO8g2UdK3B57xLJochgfk8mEqvM1PnB7yGO3Iy1idiQyEv9CfIb2XkpVDbwcDP7451JrULztCK9/5DNj+M4MOziuyiOPdaraZWGZAmineIf3PErgYkGsjtsggoXWgpahwx/s0l2rkDD8pHg7OpbOj6AvMVPSR8r1cCDXGtsWO7EQr3bffA5iRvurGGQ5+fOlDG1/wvc9pF4he0QX4OP/dI+netvxbQNB9TpH635uEEcWtA2uPjnJeg==
  template:
    metadata:
      name: ghcr-secret
      namespace: production
    type: kubernetes.io/dockerconfigjson
