kube-prometheus-stack:
  prometheusOperator:
    admissionWebhooks:
      enabled: false
    tls:
      enabled: false
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"

  prometheus:
    prometheusSpec:
      nodeSelector:
        node-group: monitor-node
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: opensearch
              topologyKey: kubernetes.io/hostname
      resources:
        requests:
          cpu: "100m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"

  grafana:
    adminPassword: "Nt548@DevOps2026!AWS"
    defaultDashboardsEnabled: false
    sidecar:
      dashboards:
        enabled: true
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"

  alertmanager:
    alertmanagerSpec:
      resources:
        requests:
          cpu: "20m"
          memory: "32Mi"
        limits:
          cpu: "100m"
          memory: "64Mi"

  kube-state-metrics:
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "64Mi"

  prometheus-node-exporter:
    resources:
      requests:
        cpu: "10m"
        memory: "16Mi"
      limits:
        cpu: "100m"
        memory: "32Mi"
