---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgAbdHF6b2+3Dd7kdTxVCp/3wJREU/RzN2iWEIgdV2seQQ3o+px7Wp/eVnuYzWbIee+GTherMXKfTlFtiP+CFTiD0RIIQChgD5v6FVjduZggDOigk1B+WEyshXHU9Nh4xGc4r18xLjo8sdJJNOelFbJAAeIkEyfZmzOQBKSl4S26kVHZw3/RPTRO/rMV/KVpoCotUVUM6l+mXo0IvLZb44SEV/xVFDY7V67v3W/QvPivyWcmQehL4tj+Dvin7BUufWDeX/RiV+7rofBgwFbnYxdpJ2h0dipbjx4H15VbR1Fd/OqLPjvex2aZisRjB910Mjz/PoWpI4vYbRJ+/Y0OoBR29e6CAG/cH2EVhRQEFTlQ4BvKZfi6ln1X5J/eh+/Sd3N3rGIreitbylkLiFDymB0Ul0TsfV6YIuIDMBGNGEk+WCTowBgSNBnhE5tmM/3d2rMJ0rCkqW0LkFHPT+Vu2dLJ2IvUbJ2V04S8WoevlduqxM0n//sfqhNRLgR1wNfh78k5uuXhJpIfRrN+P78XUQwZjYWiLGvo6JfbsZT3IsBJYol8AdVyqFWBG0HIpZNtPkjDSTDmCwpeXmcfdX/fgXQHeWu3Q3qImUF/ZHyUtKSllyEEREcgsrqLPMg8G5mYusq5nAbmG2WE9gl5aXhGeckMZg6ppY6ws8fD0Boaq31G1f/sUHthCpFbrkPxp/NQpxoj0JGyNdMdv++gwxnHoHwccE72xh4EaUaSTHhj16mufV4u8p8zvo6jYnvSy3A6FlaFj8sx14rpu4B1jHSXL5z8DrbT0vtG26g54CZXz5jMHWQ5GDo5TCKMoRUVHGHzxvIaQiEVrSuJYyO6uDKOh7DQyYOgciyGIhgjs3phgZSkUQZ8Hvu5Wr4RiDf2/YG45IthijqXb1iKK2pl32lReFD95QcA+wiKommkbp1N
  template:
    metadata:
      name: ghcr-secret
      namespace: staging
    type: kubernetes.io/dockerconfigjson
