apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: {{ .Chart.Name }}

  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}

    spec:

      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}

      nodeSelector:
        node-group: {{ .Values.nodeSelector }}

      containers:
        - name: frontend-app

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          ports:
            - containerPort: {{ .Values.service.port }}