apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: devops-app
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "add_github_username_here",
          "password": "Add_Personanl_Access_Token_Here"
      }
    }