---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opensearch-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: AgBb4hEAWlbpBBvSIXf6TYchkZv74V45bUN7RRiuIOGzz5p31DVLXv95TuxMmeoSF8TX8O6+3uW3/PynzQ5uJQUaM4pzUBu/G8eQc6YWphvV3j3vDQnl96FSJww/hQSph4/PHoquadnOm72fdGJ77XSAZdF4LlGN3R0X7/m0gYpxjPiBU/wWNUXXrd9eLqCWcaEvuRFflTqQkbMzBaEeUX7ZoDgviwrsscwuxz1ffLA/X1SCoGfrRY6nmlQxcE07cIUVovJonNBOq9hiU7y6QrzvCc5QPdkApYgWc0Vjh13zId8v28kuWty537F8YpcvS0HCzVoYnkIAUaoOaVHHVzQekuvWDxfWZ/AyqWnFIRbPalmv85MAESm5gXpHYjFL6W9v5qt9aFnDigUIfwV8LG6q+H0Nem+MpR5e5f2+g+hn1tZT+y+Cb6qUAl22Npv6lRw1p1zJdBxdJ9mMSic1gugsrtXvtFcu1wMlwbpXTbgtjUYmZvyFrDGKX/6ZD8CGC9WeN4dfnt6P06udZoNJUik7oEv9kNo20QgkIv3JmPhhumggVJpDMiuHH6Q8uOAaZCuD2r197W6HeKrj7vfAxWTlgy1JqTQFq3XijEQDBM5x0nZUKJHmAs5OgcFX7q0FYbEzjswmFGkUndodpShA7iENof6jPHciWQ+VTde3GkJEdTuEPPf6P1lPtiVWsexFuSSNdfqvQCkzqHH1HKs/gZeOd+cG9A==
  template:
    metadata:
      name: opensearch-admin-secret
      namespace: monitoring
