---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opensearch-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: AgApiEeWySDdN5LkUud9QJqwZpsaYhSf6TXffXfbkuCB0xkDZIkyYd/v4MVhBWRhQOB0Mbo5iYrY3pgKWRMG2XGJMEjJIVFIUj2WTIr7UEgPuALtFc7bLNcEeVYjSKC7M1We5/3z+hDWKjuHAFaCb+yt9jZq+o7NOt2Dt5OvPuwvmqOCd4AOINa5P/ClRdezut+REahtqqt8qRZIk/Fvh20eJaze2ARYAfz6KY/+3n+1dumwdgaDemqujmH6z4lRMVshgtXj3k98i+wxJYutdAxR34t9nPq6GklkBYje/VmkAsicoluSfNs8W9yZOPf9ndqJg+JbWnQflkOLJZqph01yDrEyBsefT7nRdA+LCAGkEcZidCcaE3QN20jSwwtFaWtYrjKYiX/RrEUvp1zQbmVkVd4fPFgiMh/ulMGVR05PopBC+9Vr49W8IaN3WqDx8kcjUcuBFeS7h8mrw+BGwRmz7V5EZwN2c4pS9Kv5W8YBrd764ZqO0uOCTyZ+5K2FGl6mrYWkX+zpFnLkW+owu+vptK710UVr8OEdIqOO61Nex8qCPo4g/f4DginC6Sbm1f32MG2HRKjQ/9UtGuvVvoLaunu4X0AJnG8ZXZ1susiEotZKsZ/fyVGg8072WeH8cLNFVievseDrKaopEV8pgspyazYbO0QalHrhNDkGqZ1T/EnJij1Vp3mi6yMOTCkgXX0TttYImaJ6JDSnug==
  template:
    metadata:
      name: opensearch-admin-secret
      namespace: monitoring
